// Where everything in the city comes from, for the data sources panel (index.html #sources): the data the
// compiler reads (tools/pipeline/fetch.mjs), the assets the client draws with, and the software under it.
export const SOURCES = [
  {
    group: 'Map data',
    items: [
      {
        name: 'OpenStreetMap', url: 'https://www.openstreetmap.org/copyright',
        what: 'Building outlines, heights and floors; streets, railways and the coastline; parks, beaches, water and paths; the names on the signs.',
        license: '© OpenStreetMap contributors, ODbL 1.0',
        via: ['Geofabrik Puerto Rico extract', 'https://download.geofabrik.de/north-america/us/puerto-rico.html'],
      },
      {
        name: 'FEMA / ORNL USA Structures', url: 'https://gis-fema.hub.arcgis.com/pages/usa-structures',
        what: 'Building heights measured by LiDAR, and building uses, where OpenStreetMap has none.',
        license: 'Public domain',
      },
    ],
  },
  {
    group: 'Elevation and imagery',
    items: [
      {
        name: 'USGS 3DEP elevation', url: 'https://www.usgs.gov/3d-elevation-program',
        what: 'The terrain, from El Morro to the hills of Caimito, and of the island around it.',
        license: 'Public domain',
        via: ['AWS Terrain Tiles (Mapzen / Tilezen)', 'https://registry.opendata.aws/terrain-tiles/'],
      },
      {
        name: 'USGS The National Map orthoimagery', url: 'https://www.usgs.gov/programs/national-geospatial-program/national-map',
        what: 'The aerial photo on the open ground and on the surrounding island.',
        license: 'Public domain',
      },
    ],
  },
  {
    group: '3D assets',
    items: [
      {
        name: 'Poly Haven', url: 'https://polyhaven.com',
        what: 'Textures: stucco, plaster and concrete walls, asphalt, pavers, grass, sand and the cobblestones of the old city.',
        license: 'CC0',
      },
      {
        name: 'ez-tree', url: 'https://github.com/dgreenheck/ez-tree',
        what: 'The shade trees and the flamboyanes (the palms are generated here).',
        license: 'MIT, Daniel Greenheck',
      },
      {
        name: 'Takram three-geospatial', url: 'https://github.com/takram-design-engineering/three-geospatial',
        what: 'The sky, the haze of distance and the volumetric clouds, with their noise textures.',
        license: 'MIT',
      },
    ],
  },
  {
    group: 'Software',
    items: [
      {
        name: 'procedural-tokyo', url: 'https://github.com/jeantimex/tokyo',
        what: 'The city engine this is a port of: tile compiler, streaming, facades, traffic and lighting.',
        license: 'MIT, jeantimex',
      },
      {
        name: 'three.js and friends', url: 'https://threejs.org',
        what: 'three.js, postprocessing, N8AO, lil-gui, earcut, polygon-clipping, osm-pbf-parser-node.',
        license: 'MIT / ISC',
      },
    ],
  },
];

// Not data: generated by the compiler and the client.
export const GENERATED = 'Generated, not mapped: window patterns, wall colours (the colonial palette of the old city included), palms, '
  + 'street lights and poles, parked and moving cars, road paint where OpenStreetMap has none, billboards and shop sign colours.';

// Fills the panel: `list` the element the sources go in, `compiled` the area's compile date (manifest.compiled).
export function renderSources(list, compiled) {
  const el = (tag, cls, text) => { const e = document.createElement(tag); if (cls) e.className = cls; if (text) e.textContent = text; return e; };
  const link = (text, href) => { const a = el('a', null, text); a.href = href; a.target = '_blank'; a.rel = 'noopener'; return a; };
  list.replaceChildren();
  list.append(el('h2', null, 'Data sources'));
  for (const { group, items } of SOURCES) {
    list.append(el('h3', null, group));
    const ul = el('ul');
    for (const s of items) {
      const li = el('li');
      li.append(link(s.name, s.url), el('p', 'what', s.what));
      const meta = el('p', 'meta', s.license);
      if (s.via) meta.append(' · via ', link(s.via[0], s.via[1]));
      li.append(meta);
      ul.append(li);
    }
    list.append(ul);
  }
  list.append(el('p', 'generated', GENERATED));
  if (compiled) list.append(el('p', 'compiled', `This city compiled ${compiled.slice(0, 10)}.`));
}
